### ISSUE TITLE
how can i use this package

### ISSUE THREAD

**Issue by lai-bluejay** [ArdalanM/pyLightGBM#2]
Hello. 
It's my first time to use cpp file and headfile for python.

If I want to use this package, May I put the LightGBM's  src into LighGBM/lightgbm? And then, I can design a classifier.

ps. Is the directory wrong? LighGBM -> LightGBM?

**Comment by lai-bluejay** [comment]
What can I do for this repo?
May I help you>?

**Comment by ArdalanM** [comment]
@lai-bluejay, here are the steps I followed:

**First step**: Install Microsoft LightGBM
- Instruction here: https://github.com/Microsoft/LightGBM/wiki/Installation-Guide
- Since I am on linux: 

``` bash
git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
mkdir build ; cd build
cmake .. 
make -j
```

**Second step**: Clone this repository and install it

``` python
git clone https://github.com/ArdalanM/pyLightGBM
cd pyLightGBM 
python setup.py install
```

**Third step**: Use the library :p

``` python
from pylightgbm.models import GBMRegressor
clf = GBMRegressor(exec_path="~/LightGBM/lightgbm")
```

Bear in mind that `exec_path` is the path of the lightgbm that you installed at step 1.

**Comment by lai-bluejay** [comment]
Thank you very much

**Comment by lai-bluejay** [comment]
I see.
After I installed and make lightgbm, then i can use it by os command line.

**Comment by lai-bluejay** [comment]
os utils seems great.

**Comment by ArdalanM** [comment]
I updated master branch, **init**.py was missing, that is why you could not install the library :)

Thanks
